# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

resources:
  pipelines:
    - pipeline: buildContosoAir
      source: cloudfyy.ContosoAir
      trigger:
        branches:
          include:
            - master

steps:

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '4fb77d9a-1df0-463c-b889-636f6f46fcf5'
    definition: '6'
    buildVersionToDownload: 'latest'
    targetPath: '$(Pipeline.Workspace)'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ME-MngEnv318848-robertdu(595c5281-dd90-4ddf-9a98-e874a28529d0)'
    subscriptionId: '595c5281-dd90-4ddf-9a98-e874a28529d0'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourcegroup)'
    location: 'eastasia'
    templateLocation: 'URL of the file'
    csmFileLink: '$(Pipeline.Workspace)/drop/deployment/azuredeploy.json'
    csmParametersFileLink: '$(Pipeline.Workspace)/drop/deployment/azuredeploy.parameters.json'
    overrideParameters: '-p_environment $(web_environment) -p_site_prefix $(web_prefix) -p_site_web_name $(web_site)'
    deploymentMode: 'Incremental'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'ME-MngEnv318848-robertdu(595c5281-dd90-4ddf-9a98-e874a28529d0)'
    appType: 'webApp'
    WebAppName: '$(web_prefix)-$(web_site)-$(web_environment)'
    packageForLinux: '$(Pipeline.Workspace)/**/*.zip'